<h2>Přihlášení do administrace</h2>
                      
<form method="post">
	Jméno<br />
	<input type="text" name="jmeno" /><br />
	Heslo<br />
	<input type="password" name="heslo" /><br />
	<div class="tlacitka">
	<a class="pojistenec" href="uvod">Zpět</a>
	<input type="submit" value="Přihlásit" />
	</div>
</form>

<p>Pokud ještě nemáte účet, <a class="odkaz" href="registrace">zaregistrujte se</a>.</p>