<h2>Registrace</h2>

<form method="post">
	Jméno<br />
	<input type="text" name="jmeno" required /><br />
	Heslo<br />
	<input type="password" name="heslo" required /><br />
	Heslo znovu<br />
	<input type="password" name="heslo_znovu" required /><br />
	Zadejte aktuální rok (antispam)<br />
	<input type="text" name="rok" required/><br />
	<div class="tlacitka">
	<a class="pojistenec" href="prihlaseni">Zpět</a>
	<input type="submit" value="Registrovat" />
	</div>
</form>